# 워크플로우
name: Github Actions 실행시켜보기

on: 
  push:
    branches:
      - main
# 워크플로우는 여러 개의 job으로 이루어질 수 있고
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
# 하나의 job은 여러 개의 step으로 이루어져 있다.
# main이라는 브랜치에 push되면 아래의 "Hello World" 작업을 실행시키란 의미
    steps:
      - name: Hello World 출력하기
        run: echo "Hello World"